@baseURL = http://localhost:3333 
@authToken = {{authentificate.response.body.accessToken}}

###
# @name authentificate
POST {{baseURL}}/authenticate
Content-Type: application/json

{
  "email": "max@test.com.br",
  "password": "123456"
}
###

# @name create_company
POST {{baseURL}}/companies
Content-Type: application/json
Authorization: Bearer {{authToken}}
 
{
    "name": "Test_Company",
    "cnpj": "41735673000177"
}
###

# @name fetch_companies
GET {{baseURL}}/companies?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{authToken}}
 

###

# @name create_base
POST {{baseURL}}/bases
Content-Type: application/json
Authorization: Bearer {{authToken}}
 
{
    "name": "Test_Base_1",
    "companyId": "103df4e9-ba40-4a8f-afe4-1e58fb60d087"
}
###

# @name fetch_bases
GET {{baseURL}}/bases/351d141d-2465-4ba3-a766-c86ae84c8a2b
Content-Type: application/json
Authorization: Bearer {{authToken}}
 

###

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "cpf" : "415.572.120-15",
    "name": "Max",
    "email": "max@test.com.br",
    "password": "123456",
    "role" : "ADMIN",
    "companyId": "103df4e9-ba40-4a8f-afe4-1e58fb60d087",
    "baseId" : "fda7e164-2de4-493f-96bb-3a3bc9823ea7"
}
###

# @name fetch_accounts
GET {{baseURL}}/accounts?ids=9d980633-057e-4674-9e55-eb7b103e6edb
Content-Type: application/json
Authorization: Bearer {{authToken}}


###
###

# @name edit_account
PUT {{baseURL}}/accounts/eb8ae346-0177-45b4-8db8-1d3b8578d6c4
Content-Type: application/json
Authorization: Bearer {{authToken}}
{
    "name": "Max Gambarini Filho",
    "email": "max@test.com.br"
}

###

# @name test_server_guards
GET  {{baseURL}}/test-guards
Content-Type: application/json
Authorization: Bearer {{authToken}}
 

 

